
image: Ubuntu

stack: python 3.6

init:
- SWMM_HOME=$APPVEYOR_BUILD_FOLDER
- BUILD_HOME=build
- TEST_HOME=nrtests
- gcc -v

install:
- python -m pip install nrtest

build_script:
- cmake -E make_directory build
- cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release ..
- cmake --build ./build

test_script:
- bash tools/before-nrtest.sh $TEST_HOME $SWMM_HOME/$BUILD_HOME/bin linux
- cd $TEST_HOME
- nrtest execute apps/swmm-linux.json  tests/examples tests/extran tests/routing tests/swc tests/update_v5111 tests/user -o benchmark/swmm-linux

on_failure:
- cd benchmark
- 7za a benchmark-linux.zip ./swmm-linux
- appveyor PushArtifact benchmark-linux.zip
- appveyor PushArtifact ../../$BUILD_HOME/CMakeCache.txt
